In [25]:
#Library

In [5]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
type(b)

numpy.ndarray

In [16]:
trans=np.transpose(b)
print(trans)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
rav=np.ravel(b)
print(rav)

[1 2 3 4 5 6 7 8 9]


In [29]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ze=np.zeros((10,10))
print(ze)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [45]:
on=np.ones((10,10))
print(on)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [49]:
np.random.random((8,2))

array([[0.57300293, 0.26716691],
       [0.5263337 , 0.86384172],
       [0.84292036, 0.88415055],
       [0.58083268, 0.63708635],
       [0.57646369, 0.64351511],
       [0.85372512, 0.1991022 ],
       [0.67896724, 0.84131882],
       [0.61132354, 0.71068443]])

In [53]:
on=np.delete(b,4)
print(on)

[1 2 3 4 6 7 8 9]
